apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dtlab.fullname" . }}-backend-env
  labels:
    {{- include "dtlab.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  JWT_EXPIRE_HOURS: {{ .Values.backend.jwtExpireHours | quote }}
