apiVersion: v1
kind: Service
metadata:
  name: {{ include "dtlab.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dtlab.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
  selector:
    {{- include "dtlab.selectorLabels" (dict "Chart" .Chart "Release" .Release "component" "postgres") | nindent 4 }}
