apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "simulator.fullname" . }}-backend-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "simulator.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
